### ISSUE TITLE
Publish 3.2

### ISSUE THREAD

**Issue by amasta** [englishtown/vertx-cassandra#13]
Hello, can you publish 3.2.0?

**Comment by adrianluisgonzalez** [comment]
The 3.2.0-SNAPSHOT is available.  Just waiting for datastax to release a stable 3.0.0 of the cassandra driver.  The current version is 3.0.0-rc1.

**Comment by jtruelove** [comment]
any plans for a build against cassandra 3.1?

**Comment by adrianluisgonzalez** [comment]
The datastax driver 3.0.0 is released.  I have published vertx-cassandra 3.2.0 to maven central.

@jtruelove I believe the datastax driver 3.0.0 is built against Cassandra 3.2.1.
https://github.com/datastax/java-driver/blob/3.0.0/pom.xml#L48
