### ISSUE TITLE
MappingManager Support

### ISSUE THREAD

**Issue by jtruelove** [englishtown/vertx-cassandra#4]
Any thoughts on exposing through an accessor the actual Cassandra Session object or a function that would initialize a mapping manager with a session and return it? The former seems a bit more flexible to me. As of right now I can't figure out a way to use vertx-cassandra with the mapping class 

http://www.datastax.com/drivers/java/2.1/com/datastax/driver/mapping/MappingManager.html

**Comment by jtruelove** [comment]
Ping just wondering if there's any update on this? If you're open to the change I can just submit a pull request. Just let me know.

**Comment by jtruelove** [comment]
just saw that it looks like you made the change here https://github.com/englishtown/vertx-cassandra/commit/913c3d06311839560931c333e1fc823a2056f156, thanks!

**Comment by adrianluisgonzalez** [comment]
Sorry, meant to update the issue.  Glad you found it.  I'll close it if there's nothing further.
