### ISSUE TITLE
releases

### ISSUE THREAD

**Issue by jtruelove** [englishtown/vertx-cassandra#5]
How often do you publish new release of the lib/mod/jar? I can just build locally and install of course but if there's some fixed frequency I like to use the public builds etc..

**Comment by adrianluisgonzalez** [comment]
SNAPSHOTS are built by a CI server triggered by any commits to the develop branch.  Non-SNAPSHOT builds don't really follow a fixed schedule, more based on my needs.  If you want a stable build, just drop me a message or open a github issue and I should be able to do one.

**Comment by jtruelove** [comment]
yeah I'd love a stable build of latest with the getSession change in it if possible

**Comment by adrianluisgonzalez** [comment]
3.0.0-RC2 is released to maven central.

**Comment by jtruelove** [comment]
Does it take a while to propagate?

don't see it here yet:
https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.englishtown%22%20AND%20a%3A%22vertx-mod-cassandra%22

or here:
http://mvnrepository.com/artifact/com.englishtown/vertx-mod-cassandra

I'm guessing it does.

**Comment by adrianluisgonzalez** [comment]
It's a vert.x 3 jar, not a module.

http://search.maven.org/#artifactdetails%7Ccom.englishtown.vertx%7Cvertx-cassandra%7C3.0.0-RC2%7Cjar

**Comment by jtruelove** [comment]
Ah gotcha, I'm not on 3 yet because it isn't out for production use yet as
far as I can tell? I'm still on 2.X.X.

**Comment by adrianluisgonzalez** [comment]
3.0.0-milestone2 is in maven central releases.  It's not the final 3.0.0 build, but it is a stable version.

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.vertx%22%20AND%20v%3A%223.0.0-milestone2%22

**Comment by jtruelove** [comment]
okay cool, I just can't take on the work to move to 3 without a bunch of
testing etc.. I totally will once it's out.

**Comment by jtruelove** [comment]
can you safely use vertx 3 jars with vertx 2 then?

**Comment by adrianluisgonzalez** [comment]
Unfortunately vert.x3 jars are not compatible with vert.x2.  I've built and deployed vertx-mod-cassandra 2.1.0

Give it 10 mins to propagate to maven central.  You can see it here: https://oss.sonatype.org/content/repositories/releases/com/englishtown/vertx-mod-cassandra/2.1.0/

**Comment by jtruelove** [comment]
Thanks man I appreciate it!
