### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jtruelove** [englishtown/vertx-cassandra#6]
I'm trying to build the project locally and I'm getting an error because I don't think the environment knows where to get the referenced parent project, how should I go about building it? I want to submit a pull request with some mapper support but need to be able to build etc.. 

[INFO] Scanning for projects...
Downloading: https://maven.cyngn.com/artifactory/repo/com/englishtown/vertx/oss-parent-vertx/2.0.0-SNAPSHOT/maven-metadata.xml
Downloading: https://maven.cyngn.com/artifactory/repo/com/englishtown/vertx/oss-parent-vertx/2.0.0-SNAPSHOT/oss-parent-vertx-2.0.0-SNAPSHOT.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.englishtown.vertx:ext-cassandra:3.0.0-SNAPSHOT (/Users/jt/osLibs/vertx-cassandra/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact com.englishtown.vertx:oss-parent-vertx:pom:2.0.0-SNAPSHOT in repo (https://maven.cyngn.com/artifactory/repo) and 'parent.relativePath' points at wrong local POM @ line 8, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by adrianluisgonzalez** [comment]
It looks like you don't have the latest code from the develop branch.  The version 3.0.0-SNAPSHOT is correct, but the artifactId should be vertx-cassandra, not ext-cassandra.
https://github.com/englishtown/vertx-cassandra/blob/develop/pom.xml#L5

This uses parent pom 
```xml
    <parent>
        <groupId>com.englishtown.vertx</groupId>
        <artifactId>oss-parent-vertx</artifactId>
        <version>2.0.0</version>
    </parent>
```

**Comment by jtruelove** [comment]
let me re-fork it just in case

**Comment by jtruelove** [comment]
Yeah looks like I had an old fork and when you fork again github just leaves you with the old one without telling you it didn't do anything.

**Comment by adrianluisgonzalez** [comment]
You can set up an upstream remote to get latest changes from the source.
https://help.github.com/articles/syncing-a-fork/

**Comment by jtruelove** [comment]
Ah that's a good tip, I'll do that next time. Just wish the UI gave you some indicator.

**Comment by adrianluisgonzalez** [comment]
@jtruelove, can this be closed?

**Comment by jtruelove** [comment]
Definitely
